name: Demo Testing

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build image
        run: podman build -t quay.io/konveyor/analyzer-lsp:latest .

      - name: build demo image
        run: podman build -f demo.Dockerfile -t localhost/testing:latest

      - name: run demo image and ensure output unchanged
        run: |
          podman run -v $(pwd)/demo-output.yaml:/analyzer-lsp/output.yaml:Z localhost/testing:latest
          git diff demo-output.yaml

      - name: save image
        run: |
          podman save -o /tmp/analyzer-lsp.tar quay.io/konveyor/analyzer-lsp:latest

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: analyzer-lsp
          path: /tmp/analyzer-lsp.tar
          retention-days: 1

  e2e:
    needs: test
    uses: konveyor/ci/.github/workflows/global-ci.yml@main
    with:
      component_name: analyzer-lsp
